spring:
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5434/jpa-specification-db
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
