server:
  servlet:
    context-path: /jpa-specification
spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
  endpoint:
    health:
      show-details: always
