version: '3.5'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - "ALLOW_ANONYMOUS_LOGIN=yes"
      - "ZOO_CLIENT_USER=client"
      - "ZOO_CLIENT_PASSWORD=client"
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - "HOSTNAME_COMMAND=docker info | grep ^Name: | cut -d' ' -f 2"
      - "KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092"
      - "KAFKA_ZOOKEEPER_USER=client"
      - "KAFKA_ZOOKEEPER_PASSWORD=client"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge