server:
  port: 8090

spring:
  application:
    name: email-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/test-email-service
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    personal: YOUR_PERSONAL
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

email-service:
  redis:
    host: localhost
    port: 6379
    password: Test123
    database: 1
  jwt:
    access-token-secret: PyPNRM8C0ia4uOGfxqPD5DTbWC6j9TWvPStp9lb7ARo0oK2mJ3pd3KL9pxA9i8bj12TbadgezxgeEByY
    expiration-ms:
      access-token: 3600000
